version: '3.3'
services:
  persistentchat:
    build: .
    restart: always
    container_name: persistentchat
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}" 
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PERSISTENTCHAT_PORT: "${PERSISTENTCHAT_PORT}"
    ports:
      - '${PERSISTENTCHAT_PORT}:${PERSISTENTCHAT_PORT}'
    expose:
      - '${PERSISTENTCHAT_PORT}'
    networks:
      - default
      - app2_default
    external_links:
      - mysql-database:mysql_database
networks:
  default: # this network (app1)
      driver: bridge
  app2_default: # external network (app2)
      external: true
